### ISSUE TITLE
List On going events

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/AsyncVoter#9]
Details in the feature test:
https://github.com/AgileVentures/AsyncVoter/blob/master/features/list_ongoing_vote.feature

**Comment by tansaku** [comment]
I think we might want to pick apart the assumption about whether we can support multiple votes in parallel

I think for simplicity we should assume only one ongoing vote at a time, but that this story is currently about getting a list of the status of all votes, e.g. one currently active and some closed ...

**Comment by juniorg** [comment]
Junior Gonzalez [10:35 AM] @channel new async vote on https://github.com/AgileVentures/AsyncVoter/issues/9 "List on-going events" Please DM me 1 (simple), 2 (medium) or 3 (hard) - discussion in ticket or here as you prefer

Sam Joseph [11:25 AM]  @jnr.gonzalez this is an interesting one - I think we might want to pick apart the assumption about whether we can support multiple votes in parallel
[11:26]  I think for simplicity we should assume only one ongoing vote at a time, but that this story is currently about getting a list of the status of all votes, e.g. one currently active and some closed ...

Junior Gonzalez [12:26 PM]  @here  we have one vote on https://github.com/AgileVentures/AsyncVoter/issues/9 "List on-going events"  [ @sysrex ]

Junior Gonzalez [1:36 PM]  @here  Results for https://github.com/AgileVentures/AsyncVoter/issues/9 "List on-going events" [ @tansaku -1, @sysrex -1, @joaopereira -2  ]

Alex Kiss [10:36 AM]  1 for me thank you

Sam Joseph [12:35 PM]  https://github.com/AgileVentures/AsyncVoter/issues/9 I vote 1 with the proviso that only 1 vote can be active at a time

João Pereira [1:08 PM]  For the story currently being voted I go with a 2 to create a new route and model to find all active votes

Junior Gonzalez [1:38]  @here we have varying opinions, shall we discuss?

Alex Kiss [1:39 PM]  we should ping @joaopereira
[1:40]  I considered it simple since its only going to show the current vote / votes if we decide to do more than one in the future
[1:40]  basically something like db.votes.find()

Junior Gonzalez [1:41 PM]  Hi @sysrex it seems that @joaopereira is currently offline
[1:42]  I believe the idea is to have only one vote open at a time
[1:42]  so I think this should also be a 1
[1:43]  Let's see what @sam @joaopereira think

João Pereira [1:52 PM]  As I said to you in the chat I voted 2 to be coherent with the previous votes because we need to create a new endpoint and create a function  on the model to retrieve these votes. The fact that we assume we have 1 or many active votes have no difference because the output should be an array to make sure we can have multiple in the future

Sam Joseph [2:13 PM]  Happy to change to 2

Alex Kiss [3:10 PM]  happy to change to 2 as well
[3:10]  though I think its a different story

Junior Gonzalez [3:24 PM]  @here so are agreed on 2
